import type { Company } from "@/types/monitor";
import { Award, Leaf, AlertTriangle, XCircle } from "lucide-react";

interface Props {
  company: Company;
}

export default function CarbonCertificate({ company }: Props) {
  const isExceeded = company.usedCredits > company.carbonCredits;
  const isZero = company.carbonCredits === 0;

  return (
    <div className={`relative overflow-hidden rounded-2xl border-2 p-6 ${
      isZero ? "border-muted bg-muted/50" : isExceeded ? "border-aqi-hazardous/30 bg-aqi-hazardous-soft" : company.status === "yellow" ? "border-aqi-moderate/30 bg-aqi-moderate-soft" : "border-aqi-good/30 bg-aqi-good-soft"
    }`}>
      {/* Watermark */}
      <div className="absolute right-4 top-4 opacity-10">
        <Leaf className="h-24 w-24" />
      </div>

      {/* Header */}
      <div className="mb-6 flex items-center gap-3">
        <div className={`rounded-full p-2 ${isZero || isExceeded ? "bg-aqi-hazardous/20" : "bg-aqi-good/20"}`}>
          {isZero || isExceeded ? <XCircle className="h-6 w-6 text-aqi-hazardous" /> : company.status === "yellow" ? <AlertTriangle className="h-6 w-6 text-aqi-moderate" /> : <Award className="h-6 w-6 text-aqi-good" />}
        </div>
        <div>
          <h3 className="font-display text-lg font-bold text-foreground">Carbon Credit Certificate</h3>
          <p className="text-xs text-muted-foreground">Government of India — Ministry of Environment</p>
        </div>
      </div>

      <div className="space-y-3 text-sm">
        <div className="flex justify-between">
          <span className="text-muted-foreground">Company Name</span>
          <span className="font-semibold text-foreground">{company.name}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-muted-foreground">Type</span>
          <span className="text-foreground">{company.type}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-muted-foreground">Location</span>
          <span className="text-foreground">{company.district}, {company.state}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-muted-foreground">Registration Date</span>
          <span className="text-foreground">{company.registrationDate}</span>
        </div>

        <div className="my-4 border-t border-border" />

        <div className="flex justify-between">
          <span className="text-muted-foreground">Carbon Credits Issued</span>
          <span className="font-display text-2xl font-bold text-foreground">{company.carbonCredits}</span>
        </div>
        <p className="text-xs text-muted-foreground">1 Carbon Credit = 1 Metric Ton of CO₂ emission permitted</p>

        <div className="flex justify-between">
          <span className="text-muted-foreground">Credits Used</span>
          <span className={`font-display text-xl font-bold ${isExceeded ? "text-aqi-hazardous" : "text-foreground"}`}>{company.usedCredits}</span>
        </div>

        {isExceeded && (
          <div className="rounded-lg bg-destructive/10 p-3">
            <p className="font-semibold text-destructive">⚠ Exceeded by {company.usedCredits - company.carbonCredits} metric tons</p>
            <p className="mt-1 text-xs text-destructive/80">Fine applicable: ₹{((company.usedCredits - company.carbonCredits) * 15000).toLocaleString()}</p>
          </div>
        )}

        {company.fines.length > 0 && (
          <div className="mt-4 space-y-2">
            <p className="text-xs font-semibold uppercase text-muted-foreground">Fine History</p>
            {company.fines.map((f, i) => (
              <div key={i} className="rounded-md bg-destructive/5 p-2 text-xs">
                <span className="font-semibold text-destructive">₹{f.amount.toLocaleString()}</span> — {f.date} — {f.reason}
              </div>
            ))}
          </div>
        )}

        <div className="mt-4 text-center text-xs text-muted-foreground">
          Certificate ID: {company.id} • Auto-generated by Monitor India Platform
        </div>
      </div>
    </div>
  );
}
